create extension if not exists "postgis" with schema "extensions";

drop extension if exists "pg_net";

create type "public"."user_roles" as enum ('admin', 'editor', 'reader', 'creator');


  create table "public"."associations" (
    "created_at" timestamp with time zone not null default now(),
    "nom" character varying not null,
    "acronyme" text,
    "desc" text not null,
    "type_org" text not null,
    "type_org_autre" character varying,
    "annee_creation" smallint not null,
    "secteurs_interv" character varying[] not null,
    "secteurs_interv_autre" text,
    "province" text,
    "territoire" text,
    "zone_sante" text,
    "aire_sante" text,
    "localite" text,
    "latitude" double precision not null,
    "longitude" double precision not null,
    "altitude" double precision,
    "precision" double precision,
    "budget_2022" integer,
    "budget_2023" integer,
    "budget_2024" integer,
    "nb_salaries" smallint not null default '0'::smallint,
    "nb_benevoles" smallint not null default '0'::smallint,
    "nom_resp_edition" character varying not null,
    "email_resp_edition" character varying not null,
    "email_org" character varying not null,
    "nom_contact" character varying not null,
    "tel_contact" character varying not null,
    "email_contact" character varying not null,
    "website" character varying,
    "facebook" character varying,
    "twitter" character varying,
    "instagram" character varying,
    "linkedin" character varying,
    "tiktok" character varying,
    "autre_social_media" character varying,
    "updated_at" timestamp without time zone not null default now(),
    "id" uuid not null default gen_random_uuid(),
    "logo_url" character varying,
    "budget_2025" integer,
    "budget_2026" integer,
    "created_by" uuid
      );


alter table "public"."associations" enable row level security;


  create table "public"."associations_maj" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "nom" character varying not null,
    "acronyme" text,
    "desc" text not null,
    "type_org" character varying not null,
    "type_org_autre" character varying,
    "annee_creation" smallint not null,
    "secteurs_interv" character varying[] not null,
    "secteurs_interv_autre" character varying,
    "province" character varying not null,
    "territoire" character varying not null,
    "zone_sante" character varying not null,
    "aire_sante" character varying not null,
    "localite" character varying not null,
    "latitude" double precision not null,
    "longitude" double precision not null,
    "altitude" double precision,
    "precision" double precision,
    "budget_2022" integer,
    "budget_2023" integer,
    "budget_2024" integer,
    "nb_salaries" smallint not null default '0'::smallint,
    "nb_benevoles" smallint not null default '0'::smallint,
    "nom_resp_edition" character varying not null,
    "email_resp_edition" character varying not null,
    "email_org" character varying not null,
    "nom_contact" character varying not null,
    "tel_contact" character varying not null,
    "email_contact" character varying not null,
    "website" character varying,
    "facebook" character varying,
    "twitter" character varying,
    "instagram" character varying,
    "linkedin" character varying,
    "tiktok" character varying,
    "autre_social_media" character varying,
    "user_id" uuid not null,
    "association_id" uuid not null default gen_random_uuid(),
    "logo_url" character varying,
    "budget_2025" integer,
    "budget_2026" integer,
    "created_by" uuid
      );


alter table "public"."associations_maj" enable row level security;


  create table "public"."associations_new" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "nom" character varying not null,
    "acronyme" text,
    "desc" text not null,
    "type_org" text not null,
    "type_org_autre" character varying,
    "annee_creation" smallint not null,
    "secteurs_interv" character varying[] not null,
    "secteurs_interv_autre" text,
    "province" text,
    "territoire" text,
    "zone_sante" text,
    "aire_sante" text,
    "localite" text,
    "latitude" double precision not null,
    "longitude" double precision not null,
    "altitude" double precision,
    "precision" double precision,
    "budget_2022" integer,
    "budget_2023" integer,
    "budget_2024" integer,
    "nb_salaries" smallint not null default '0'::smallint,
    "nb_benevoles" smallint not null default '0'::smallint,
    "nom_resp_edition" character varying not null,
    "email_resp_edition" character varying not null,
    "email_org" character varying not null,
    "nom_contact" character varying not null,
    "tel_contact" character varying not null,
    "email_contact" character varying not null,
    "website" character varying,
    "facebook" character varying,
    "twitter" character varying,
    "instagram" character varying,
    "linkedin" character varying,
    "tiktok" character varying,
    "autre_social_media" character varying,
    "updated_at" timestamp without time zone not null default now(),
    "logo_url" character varying,
    "budget_2025" integer,
    "budget_2026" integer,
    "created_by" uuid
      );


alter table "public"."associations_new" enable row level security;


  create table "public"."projets" (
    "id" uuid not null default gen_random_uuid(),
    "intitule_projet" text not null,
    "partenaire_financier_technique" text not null,
    "noms_bailleurs_fonds" text[],
    "autre_bailleur_fonds" text,
    "secteurs_intervention" text[] not null,
    "autre_secteur_intervention" text,
    "date_debut_projet" date,
    "date_fin_projet" date,
    "statut_projet" text,
    "province" text[],
    "territoire" text[],
    "aire_sante" text,
    "localite_village_quartier" text,
    "budget_projet" numeric(15,2) not null,
    "types_services_fournis" text[] not null,
    "autre_type_services_fournis" text,
    "types_beneficiaires_populations_cibles" text[] not null,
    "autre_types_beneficiaires_populations_cibles" text,
    "nombre_total_personnes_cibles" integer not null,
    "nombre_hommes" integer,
    "nombre_femmes" integer,
    "nombre_filles" integer,
    "nombre_garcons" integer,
    "nombre_personnes_atteintes" integer,
    "nombre_personnes_handicapees" integer,
    "nombre_hommes_agees" integer,
    "association_id" uuid not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "created_by" uuid not null default auth.uid(),
    "zone_sante" text[],
    "consortium" boolean not null default false,
    "partenaires_consortium" text,
    "nombre_femmes_agees" integer
      );


alter table "public"."projets" enable row level security;


  create table "public"."projets_maj" (
    "id" bigint generated by default as identity not null,
    "intitule_projet" text not null,
    "partenaire_financier_technique" text not null,
    "noms_bailleurs_fonds" text[] not null,
    "autre_bailleur_fonds" text,
    "secteurs_intervention" text[] not null,
    "autre_secteur_intervention" text,
    "date_debut_projet" date,
    "date_fin_projet" date,
    "statut_projet" text,
    "province" text[] not null,
    "territoire" text[] not null,
    "aire_sante" text not null,
    "localite_village_quartier" text not null,
    "budget_projet" numeric(15,2) not null,
    "types_services_fournis" text[] not null,
    "autre_type_services_fournis" text,
    "types_beneficiaires_populations_cibles" text[] not null,
    "autre_types_beneficiaires_populations_cibles" text,
    "nombre_total_personnes_cibles" integer not null,
    "nombre_hommes" integer,
    "nombre_femmes" integer,
    "nombre_filles" integer,
    "nombre_garcons" integer,
    "nombre_personnes_atteintes" integer,
    "nombre_personnes_handicapees" integer,
    "nombre_hommes_agees" integer,
    "association_id" uuid not null,
    "projet_id" uuid not null,
    "created_by" uuid not null default auth.uid(),
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "zone_sante" text[],
    "consortium" boolean not null default false,
    "partenaires_consortium" text,
    "nombre_femmes_agees" integer
      );


alter table "public"."projets_maj" enable row level security;


  create table "public"."projets_new" (
    "id" bigint generated by default as identity not null,
    "intitule_projet" text not null,
    "partenaire_financier_technique" text not null,
    "noms_bailleurs_fonds" text[] not null,
    "autre_bailleur_fonds" text,
    "secteurs_intervention" text[] not null,
    "autre_secteur_intervention" text,
    "date_debut_projet" date,
    "date_fin_projet" date,
    "statut_projet" text,
    "province" text[] not null,
    "territoire" text[] not null,
    "aire_sante" text not null,
    "localite_village_quartier" text not null,
    "budget_projet" numeric(15,2) not null,
    "types_services_fournis" text[] not null,
    "autre_type_services_fournis" text,
    "types_beneficiaires_populations_cibles" text[] not null,
    "autre_types_beneficiaires_populations_cibles" text,
    "nombre_total_personnes_cibles" integer not null,
    "nombre_hommes" integer,
    "nombre_femmes" integer,
    "nombre_filles" integer,
    "nombre_garcons" integer,
    "nombre_personnes_atteintes" integer,
    "nombre_personnes_handicapees" integer,
    "nombre_hommes_agees" integer,
    "association_id" uuid not null,
    "created_by" uuid not null default auth.uid(),
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "zone_sante" text[],
    "consortium" boolean not null default false,
    "partenaires_consortium" text,
    "nombre_femmes_agees" integer
      );


alter table "public"."projets_new" enable row level security;


  create table "public"."provinces" (
    "id" smallint generated by default as identity not null,
    "province" text not null default ''::text,
    "province_c" text not null,
    "centroid" extensions.geometry
      );


alter table "public"."provinces" enable row level security;


  create table "public"."territoires" (
    "id" smallint generated by default as identity not null,
    "province_c" text not null,
    "territoire" text not null,
    "territoire_c" text not null,
    "centroid" extensions.geometry
      );


alter table "public"."territoires" enable row level security;


  create table "public"."user_profiles" (
    "id" uuid not null,
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone default now(),
    "first_name" text not null,
    "last_name" text not null,
    "role" public.user_roles not null default 'reader'::public.user_roles,
    "edit_association_id" uuid,
    "email" character varying not null
      );


alter table "public"."user_profiles" enable row level security;


  create table "public"."zones_sante" (
    "id" smallint generated by default as identity not null,
    "territoire_c" text not null,
    "zone_sante" text not null,
    "province_c" text not null,
    "zone_sante_c" text not null,
    "centroid" extensions.geometry
      );


alter table "public"."zones_sante" enable row level security;

CREATE UNIQUE INDEX associations_id_key ON public.associations USING btree (id);

CREATE UNIQUE INDEX associations_maj_nom_key ON public.associations_maj USING btree (nom);

CREATE UNIQUE INDEX associations_maj_pkey ON public.associations_maj USING btree (id);

CREATE UNIQUE INDEX associations_new_nom_key ON public.associations_new USING btree (nom);

CREATE UNIQUE INDEX associations_new_pkey ON public.associations_new USING btree (id);

CREATE UNIQUE INDEX associations_nom_key ON public.associations USING btree (nom);

CREATE UNIQUE INDEX associations_pkey ON public.associations USING btree (id);

CREATE UNIQUE INDEX projets_maj_pkey ON public.projets_maj USING btree (id);

CREATE UNIQUE INDEX projets_new_pkey ON public.projets_new USING btree (id);

CREATE UNIQUE INDEX projets_pkey ON public.projets USING btree (id);

CREATE UNIQUE INDEX provinces_id_key ON public.provinces USING btree (id);

CREATE UNIQUE INDEX provinces_pkey ON public.provinces USING btree (id);

CREATE UNIQUE INDEX provinces_province_c_key ON public.provinces USING btree (province_c);

CREATE UNIQUE INDEX provinces_province_key ON public.provinces USING btree (province);

CREATE UNIQUE INDEX territoires_id_key ON public.territoires USING btree (id);

CREATE UNIQUE INDEX territoires_pkey ON public.territoires USING btree (id);

CREATE UNIQUE INDEX territoires_territoire_c_key ON public.territoires USING btree (territoire_c);

CREATE UNIQUE INDEX territoires_territoire_key ON public.territoires USING btree (territoire);

CREATE UNIQUE INDEX user_profiles_edit_association_id_key ON public.user_profiles USING btree (edit_association_id);

CREATE UNIQUE INDEX user_profiles_email_key ON public.user_profiles USING btree (email);

CREATE UNIQUE INDEX user_profiles_pkey ON public.user_profiles USING btree (id);

CREATE UNIQUE INDEX zones_sante_pkey ON public.zones_sante USING btree (id);

CREATE UNIQUE INDEX zones_sante_zone_sante_c_key ON public.zones_sante USING btree (zone_sante_c);

alter table "public"."associations" add constraint "associations_pkey" PRIMARY KEY using index "associations_pkey";

alter table "public"."associations_maj" add constraint "associations_maj_pkey" PRIMARY KEY using index "associations_maj_pkey";

alter table "public"."associations_new" add constraint "associations_new_pkey" PRIMARY KEY using index "associations_new_pkey";

alter table "public"."projets" add constraint "projets_pkey" PRIMARY KEY using index "projets_pkey";

alter table "public"."projets_maj" add constraint "projets_maj_pkey" PRIMARY KEY using index "projets_maj_pkey";

alter table "public"."projets_new" add constraint "projets_new_pkey" PRIMARY KEY using index "projets_new_pkey";

alter table "public"."provinces" add constraint "provinces_pkey" PRIMARY KEY using index "provinces_pkey";

alter table "public"."territoires" add constraint "territoires_pkey" PRIMARY KEY using index "territoires_pkey";

alter table "public"."user_profiles" add constraint "user_profiles_pkey" PRIMARY KEY using index "user_profiles_pkey";

alter table "public"."zones_sante" add constraint "zones_sante_pkey" PRIMARY KEY using index "zones_sante_pkey";

alter table "public"."associations" add constraint "associations_created_by_fkey" FOREIGN KEY (created_by) REFERENCES public.user_profiles(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."associations" validate constraint "associations_created_by_fkey";

alter table "public"."associations" add constraint "associations_id_key" UNIQUE using index "associations_id_key";

alter table "public"."associations" add constraint "associations_nom_key" UNIQUE using index "associations_nom_key";

alter table "public"."associations_maj" add constraint "associations_maj_association_id_fkey" FOREIGN KEY (association_id) REFERENCES public.associations(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."associations_maj" validate constraint "associations_maj_association_id_fkey";

alter table "public"."associations_maj" add constraint "associations_maj_created_by_fkey" FOREIGN KEY (created_by) REFERENCES public.user_profiles(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."associations_maj" validate constraint "associations_maj_created_by_fkey";

alter table "public"."associations_maj" add constraint "associations_maj_nom_key" UNIQUE using index "associations_maj_nom_key";

alter table "public"."associations_new" add constraint "associations_new_created_by_fkey" FOREIGN KEY (created_by) REFERENCES public.user_profiles(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."associations_new" validate constraint "associations_new_created_by_fkey";

alter table "public"."associations_new" add constraint "associations_new_nom_key" UNIQUE using index "associations_new_nom_key";

alter table "public"."projets" add constraint "projets_association_id_fkey1" FOREIGN KEY (association_id) REFERENCES public.associations(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."projets" validate constraint "projets_association_id_fkey1";

alter table "public"."projets" add constraint "projets_created_by_fkey" FOREIGN KEY (created_by) REFERENCES public.user_profiles(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."projets" validate constraint "projets_created_by_fkey";

alter table "public"."projets_maj" add constraint "projet_maj_projet_id" FOREIGN KEY (projet_id) REFERENCES public.projets(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."projets_maj" validate constraint "projet_maj_projet_id";

alter table "public"."projets_maj" add constraint "projets_maj_association_id_fkey" FOREIGN KEY (association_id) REFERENCES public.associations(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."projets_maj" validate constraint "projets_maj_association_id_fkey";

alter table "public"."projets_maj" add constraint "projets_maj_created_by_fkey" FOREIGN KEY (created_by) REFERENCES public.user_profiles(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."projets_maj" validate constraint "projets_maj_created_by_fkey";

alter table "public"."projets_new" add constraint "projets_new_association_id_fkey" FOREIGN KEY (association_id) REFERENCES public.associations(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."projets_new" validate constraint "projets_new_association_id_fkey";

alter table "public"."projets_new" add constraint "projets_new_created_by_fkey" FOREIGN KEY (created_by) REFERENCES public.user_profiles(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."projets_new" validate constraint "projets_new_created_by_fkey";

alter table "public"."provinces" add constraint "provinces_id_key" UNIQUE using index "provinces_id_key";

alter table "public"."provinces" add constraint "provinces_province_c_key" UNIQUE using index "provinces_province_c_key";

alter table "public"."provinces" add constraint "provinces_province_key" UNIQUE using index "provinces_province_key";

alter table "public"."territoires" add constraint "territoires_id_key" UNIQUE using index "territoires_id_key";

alter table "public"."territoires" add constraint "territoires_province_c_fkey" FOREIGN KEY (province_c) REFERENCES public.provinces(province_c) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."territoires" validate constraint "territoires_province_c_fkey";

alter table "public"."territoires" add constraint "territoires_territoire_c_key" UNIQUE using index "territoires_territoire_c_key";

alter table "public"."territoires" add constraint "territoires_territoire_key" UNIQUE using index "territoires_territoire_key";

alter table "public"."user_profiles" add constraint "user_profiles_edit_association_id_fkey" FOREIGN KEY (edit_association_id) REFERENCES public.associations(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."user_profiles" validate constraint "user_profiles_edit_association_id_fkey";

alter table "public"."user_profiles" add constraint "user_profiles_edit_association_id_key" UNIQUE using index "user_profiles_edit_association_id_key";

alter table "public"."user_profiles" add constraint "user_profiles_email_key" UNIQUE using index "user_profiles_email_key";

alter table "public"."user_profiles" add constraint "user_profiles_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."user_profiles" validate constraint "user_profiles_id_fkey";

alter table "public"."zones_sante" add constraint "zones_sante_province_c_fkey" FOREIGN KEY (province_c) REFERENCES public.provinces(province_c) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."zones_sante" validate constraint "zones_sante_province_c_fkey";

alter table "public"."zones_sante" add constraint "zones_sante_territoire_c_fkey" FOREIGN KEY (territoire_c) REFERENCES public.territoires(territoire_c) not valid;

alter table "public"."zones_sante" validate constraint "zones_sante_territoire_c_fkey";

alter table "public"."zones_sante" add constraint "zones_sante_zone_sante_c_key" UNIQUE using index "zones_sante_zone_sante_c_key";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.assign_association_to_user(user_id uuid, association_id uuid)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$

DECLARE
  v_admin_check BOOLEAN;
BEGIN
  -- Check rights
  SELECT EXISTS (
    SELECT 1 FROM public.user_profiles 
    WHERE id = auth.uid() AND role = 'admin'
  ) INTO v_admin_check;
  
  IF NOT v_admin_check THEN
    RAISE EXCEPTION '403: Forbidden';
  END IF;
  
  -- Update profile
  UPDATE public.user_profiles 
  SET edit_association_id = association_id, updated_at = NOW()
  WHERE id = user_id;
  
  IF NOT FOUND THEN
    RAISE EXCEPTION '404: Not found';
  END IF;
  
  RETURN TRUE;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.check_user_has_edit_association()
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$BEGIN
  RETURN EXISTS (
    SELECT 1 FROM public.user_profiles 
    WHERE id = auth.uid() AND role = 'editor' AND edit_association_id IS NOT NULL
  );
EXCEPTION
  WHEN OTHERS THEN
    RETURN FALSE;
END;$function$
;

CREATE OR REPLACE FUNCTION public.check_user_is_creator()
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  -- Vérifier que l'utilisateur est authentifié
  IF auth.uid() IS NULL THEN
    RETURN FALSE;
  END IF;

  RETURN EXISTS (
    SELECT 1 FROM public.user_profiles 
    WHERE id = auth.uid() AND role = 'creator'
  );
EXCEPTION
  WHEN OTHERS THEN
    RETURN FALSE;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.get_db_stats(p_asso uuid DEFAULT NULL::uuid, p_province text[] DEFAULT NULL::text[], p_territory text[] DEFAULT NULL::text[], p_healthzone text[] DEFAULT NULL::text[], p_year integer[] DEFAULT NULL::integer[], p_intervention_sector text[] DEFAULT NULL::text[])
 RETURNS json
 LANGUAGE plpgsql
AS $function$DECLARE
  result json;
BEGIN
  SELECT json_build_object(
    'ngos_count', (
      SELECT COUNT(*)
      FROM associations a
      WHERE (p_asso IS NULL OR a.id = p_asso)
        AND (p_province IS NULL OR a.province = ANY(p_province))
        AND (p_territory IS NULL OR a.territoire = ANY(p_territory))
        AND (p_healthzone IS NULL OR a.zone_sante = ANY(p_healthzone))
        AND (p_intervention_sector IS NULL OR a.secteurs_interv && p_intervention_sector::varchar[])
    ),
    
    'projects_count', (
      SELECT COUNT(*)
      FROM projets p
      WHERE (p_asso IS NULL OR p.association_id = p_asso)
        AND (p_province IS NULL OR (p.province IS NOT NULL AND p.province && p_province))
        AND (p_territory IS NULL OR (p.territoire IS NOT NULL AND p.territoire && p_territory))
        AND (p_healthzone IS NULL OR (p.zone_sante IS NOT NULL AND p.zone_sante && p_healthzone))
        AND (p_year IS NULL OR (
             p.date_debut_projet IS NOT NULL AND EXTRACT(YEAR FROM p.date_debut_projet) = ANY(p_year)
             OR p.date_fin_projet IS NOT NULL AND EXTRACT(YEAR FROM p.date_fin_projet) = ANY(p_year)
        ))
        AND (p_intervention_sector IS NULL OR p.secteurs_intervention && p_intervention_sector)
    ),
    
    'budget_count', COALESCE((
      SELECT SUM(p.budget_projet)
      FROM projets p
      WHERE (p_asso IS NULL OR p.association_id = p_asso)
        AND (p_province IS NULL OR (p.province IS NOT NULL AND p.province && p_province))
        AND (p_territory IS NULL OR (p.territoire IS NOT NULL AND p.territoire && p_territory))
        AND (p_healthzone IS NULL OR (p.zone_sante IS NOT NULL AND p.zone_sante && p_healthzone))
        AND (p_year IS NULL OR (
             p.date_debut_projet IS NOT NULL AND EXTRACT(YEAR FROM p.date_debut_projet) = ANY(p_year)
             OR p.date_fin_projet IS NOT NULL AND EXTRACT(YEAR FROM p.date_fin_projet) = ANY(p_year)
        ))
        AND (p_intervention_sector IS NULL OR p.secteurs_intervention && p_intervention_sector)
    ), 0),
    
    'territories_count', (
      SELECT COUNT(DISTINCT t.territory)
      FROM projets p
      CROSS JOIN LATERAL unnest(p.territoire) AS t(territory)
      WHERE p.territoire IS NOT NULL
        AND (p_asso IS NULL OR p.association_id = p_asso)
        AND (p_province IS NULL OR (p.province IS NOT NULL AND p.province && p_province))
        AND (p_territory IS NULL OR (p.territoire && p_territory))
        AND (p_healthzone IS NULL OR (p.zone_sante IS NOT NULL AND p.zone_sante && p_healthzone))
        AND (p_year IS NULL OR (
             p.date_debut_projet IS NOT NULL AND EXTRACT(YEAR FROM p.date_debut_projet) = ANY(p_year)
             OR p.date_fin_projet IS NOT NULL AND EXTRACT(YEAR FROM p.date_fin_projet) = ANY(p_year)
        ))
        AND (p_intervention_sector IS NULL OR p.secteurs_intervention && p_intervention_sector)
    ),
    
    'interventions_fields_count', (
      SELECT COUNT(DISTINCT s.secteur)
      FROM projets p
      CROSS JOIN LATERAL unnest(p.secteurs_intervention) AS s(secteur)
      WHERE p.secteurs_intervention IS NOT NULL
        AND (p_asso IS NULL OR p.association_id = p_asso)
        AND (p_province IS NULL OR (p.province IS NOT NULL AND p.province && p_province))
        AND (p_territory IS NULL OR (p.territoire IS NOT NULL AND p.territoire && p_territory))
        AND (p_healthzone IS NULL OR (p.zone_sante IS NOT NULL AND p.zone_sante && p_healthzone))
        AND (p_year IS NULL OR (
             p.date_debut_projet IS NOT NULL AND EXTRACT(YEAR FROM p.date_debut_projet) = ANY(p_year)
             OR p.date_fin_projet IS NOT NULL AND EXTRACT(YEAR FROM p.date_fin_projet) = ANY(p_year)
        ))
        AND (p_intervention_sector IS NULL OR p.secteurs_intervention && p_intervention_sector)
    ),
    
    'interventions_fields_details', COALESCE((
      SELECT json_agg(
               json_build_object(
                 'secteur', x.secteur,
                 'occurrences', x.occurrences
               )
               ORDER BY x.occurrences DESC
             )
      FROM (
        SELECT s.secteur, COUNT(*) AS occurrences
        FROM projets p
        CROSS JOIN LATERAL unnest(p.secteurs_intervention) AS s(secteur)
        WHERE p.secteurs_intervention IS NOT NULL
          AND (p_asso IS NULL OR p.association_id = p_asso)
          AND (p_province IS NULL OR (p.province IS NOT NULL AND p.province && p_province))
          AND (p_territory IS NULL OR (p.territoire IS NOT NULL AND p.territoire && p_territory))
          AND (p_healthzone IS NULL OR (p.zone_sante IS NOT NULL AND p.zone_sante && p_healthzone))
          AND (p_year IS NULL OR (
               p.date_debut_projet IS NOT NULL AND EXTRACT(YEAR FROM p.date_debut_projet) = ANY(p_year)
               OR p.date_fin_projet IS NOT NULL AND EXTRACT(YEAR FROM p.date_fin_projet) = ANY(p_year)
          ))
          AND (p_intervention_sector IS NULL OR p.secteurs_intervention && p_intervention_sector)
        GROUP BY s.secteur
      ) AS x
    ), '[]'::json),
    
    'beneficiaries_types_details', COALESCE((
      SELECT json_agg(
               json_build_object(
                 'type', x.type,
                 'occurrences', x.occurrences,
                 'percentage', ROUND(100.0 * x.occurrences / total.total_count, 2)
               )
               ORDER BY x.occurrences DESC
             )
      FROM (
        SELECT unnest(p.types_beneficiaires_populations_cibles) AS type, COUNT(*) AS occurrences
        FROM projets p
        WHERE p.types_beneficiaires_populations_cibles IS NOT NULL
          AND (p_asso IS NULL OR p.association_id = p_asso)
          AND (p_province IS NULL OR (p.province IS NOT NULL AND p.province && p_province))
          AND (p_territory IS NULL OR (p.territoire IS NOT NULL AND p.territoire && p_territory))
          AND (p_healthzone IS NULL OR (p.zone_sante IS NOT NULL AND p.zone_sante && p_healthzone))
          AND (p_year IS NULL OR (
               p.date_debut_projet IS NOT NULL AND EXTRACT(YEAR FROM p.date_debut_projet) = ANY(p_year)
               OR p.date_fin_projet IS NOT NULL AND EXTRACT(YEAR FROM p.date_fin_projet) = ANY(p_year)
          ))
          AND (p_intervention_sector IS NULL OR p.secteurs_intervention && p_intervention_sector)
        GROUP BY type
      ) x
      CROSS JOIN (
        SELECT COUNT(*) AS total_count
        FROM projets p,
        unnest(p.types_beneficiaires_populations_cibles)
        WHERE p.types_beneficiaires_populations_cibles IS NOT NULL
          AND (p_asso IS NULL OR p.association_id = p_asso)
          AND (p_province IS NULL OR (p.province IS NOT NULL AND p.province && p_province))
          AND (p_territory IS NULL OR (p.territoire IS NOT NULL AND p.territoire && p_territory))
          AND (p_healthzone IS NULL OR (p.zone_sante IS NOT NULL AND p.zone_sante && p_healthzone))
          AND (p_year IS NULL OR (
               p.date_debut_projet IS NOT NULL AND EXTRACT(YEAR FROM p.date_debut_projet) = ANY(p_year)
               OR p.date_fin_projet IS NOT NULL AND EXTRACT(YEAR FROM p.date_fin_projet) = ANY(p_year)
          ))
          AND (p_intervention_sector IS NULL OR p.secteurs_intervention && p_intervention_sector)
      ) total
    ), '[]'::json),
    
    'beneficiaries_count', COALESCE((
      SELECT json_build_object(
        'target', SUM(p.nombre_total_personnes_cibles),
        'beneficiaries', SUM(p.nombre_personnes_atteintes)
      )
      FROM projets p
      WHERE (p_asso IS NULL OR p.association_id = p_asso)
        AND (p_province IS NULL OR (p.province IS NOT NULL AND p.province && p_province))
        AND (p_territory IS NULL OR (p.territoire IS NOT NULL AND p.territoire && p_territory))
        AND (p_healthzone IS NULL OR (p.zone_sante IS NOT NULL AND p.zone_sante && p_healthzone))
        AND (p_year IS NULL OR (
             p.date_debut_projet IS NOT NULL AND EXTRACT(YEAR FROM p.date_debut_projet) = ANY(p_year)
             OR p.date_fin_projet IS NOT NULL AND EXTRACT(YEAR FROM p.date_fin_projet) = ANY(p_year)
        ))
        AND (p_intervention_sector IS NULL OR p.secteurs_intervention && p_intervention_sector)
    ), json_build_object('target', 0, 'beneficiaries', 0)),
    
    'beneficiaries_profile_details', COALESCE((
      SELECT json_build_object(
        'nb_men', COALESCE(SUM(p.nombre_hommes), 0),
        'nb_women', COALESCE(SUM(p.nombre_femmes), 0),
        'nb_girls', COALESCE(SUM(p.nombre_filles), 0),
        'nb_boys', COALESCE(SUM(p.nombre_garcons), 0),
        'nb_disabled', COALESCE(SUM(p.nombre_personnes_handicapees), 0),
        'nb_old_men', COALESCE(SUM(p.nombre_hommes_agees), 0),
        'nb_old_women', COALESCE(SUM(p.nombre_femmes_agees), 0),
        'total_population', COALESCE(
          COALESCE(SUM(p.nombre_hommes), 0) + 
          COALESCE(SUM(p.nombre_femmes), 0) + 
          COALESCE(SUM(p.nombre_filles), 0) + 
          COALESCE(SUM(p.nombre_garcons), 0) + 
          COALESCE(SUM(p.nombre_hommes_agees), 0) + 
          COALESCE(SUM(p.nombre_femmes_agees), 0), 0
        )
      )
      FROM projets p
      WHERE (p_asso IS NULL OR p.association_id = p_asso)
        AND (p_province IS NULL OR (p.province IS NOT NULL AND p.province && p_province))
        AND (p_territory IS NULL OR (p.territoire IS NOT NULL AND p.territoire && p_territory))
        AND (p_healthzone IS NULL OR (p.zone_sante IS NOT NULL AND p.zone_sante && p_healthzone))
        AND (p_year IS NULL OR (
             p.date_debut_projet IS NOT NULL AND EXTRACT(YEAR FROM p.date_debut_projet) = ANY(p_year)
             OR p.date_fin_projet IS NOT NULL AND EXTRACT(YEAR FROM p.date_fin_projet) = ANY(p_year)
        ))
        AND (p_intervention_sector IS NULL OR p.secteurs_intervention && p_intervention_sector)
    ), json_build_object('nb_men', 0, 'nb_women', 0, 'nb_girls', 0, 'nb_boys', 0, 'nb_disabled', 0, 'nb_old_men', 0, 'nb_old_women', 0, 'total_population', 0))
  )
  INTO result;

  RETURN result;
END;$function$
;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_catalog'
AS $function$DECLARE
  matching_association_id UUID;
BEGIN
  SELECT id
    INTO matching_association_id
  FROM public.associations
  WHERE LOWER(email_resp_edition) = LOWER(NEW.email);

  INSERT INTO public.user_profiles (
    id,
    email,
    first_name,
    last_name,
    edit_association_id,
    role
  ) VALUES (
    NEW.id,
    NEW.email,
    NEW.raw_user_meta_data ->> 'first_name',
    NEW.raw_user_meta_data ->> 'last_name',
    matching_association_id,
    CASE
      WHEN matching_association_id IS NOT NULL THEN 'editor'::"user_roles"
      ELSE 'reader'::"user_roles"
    END
  );

  RETURN NEW;
END;$function$
;

CREATE OR REPLACE FUNCTION public.is_admin()
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM public.user_profiles 
    WHERE id = auth.uid() AND role = 'admin'
  );
END;

$function$
;

CREATE OR REPLACE FUNCTION public.submit_association_update(association_id uuid, nom text, acronyme text, "desc" text, type_org text, type_org_autre text, annee_creation smallint, secteurs_interv text[], secteurs_interv_autre text, province text, territoire text, zone_sante text, aire_sante text, localite text, latitude double precision, longitude double precision, altitude double precision, "precision" double precision, budget_2022 integer, budget_2023 integer, budget_2024 integer, budget_2025 integer, budget_2026 integer, nb_salaries smallint, nb_benevoles smallint, nom_resp_edition text, email_resp_edition text, email_org text, nom_contact text, tel_contact text, email_contact text, website text, facebook text, twitter text, instagram text, linkedin text, tiktok text, autre_social_media text, logo_url text)
 RETURNS bigint
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  v_user_profile RECORD;
  v_modification_id BIGINT;
  -- Déclarer des variables locales pour éviter l'ambiguïté
  v_association_id UUID := submit_association_update.association_id;
  v_nom TEXT := submit_association_update.nom;
  v_acronyme TEXT := submit_association_update.acronyme;
  v_desc TEXT := submit_association_update."desc";
  v_type_org TEXT := submit_association_update.type_org;
  v_type_org_autre TEXT := submit_association_update.type_org_autre;
  v_annee_creation SMALLINT := submit_association_update.annee_creation;
  v_secteurs_interv TEXT[] := submit_association_update.secteurs_interv;
  v_secteurs_interv_autre TEXT := submit_association_update.secteurs_interv_autre;
  v_province TEXT := submit_association_update.province;
  v_territoire TEXT := submit_association_update.territoire;
  v_zone_sante TEXT := submit_association_update.zone_sante;
  v_aire_sante TEXT := submit_association_update.aire_sante;
  v_localite TEXT := submit_association_update.localite;
  v_latitude DOUBLE PRECISION := submit_association_update.latitude;
  v_longitude DOUBLE PRECISION := submit_association_update.longitude;
  v_altitude DOUBLE PRECISION := submit_association_update.altitude;
  v_precision DOUBLE PRECISION := submit_association_update."precision";
  v_budget_2022 INTEGER := submit_association_update.budget_2022;
  v_budget_2023 INTEGER := submit_association_update.budget_2023;
  v_budget_2024 INTEGER := submit_association_update.budget_2024;
  v_budget_2025 INTEGER := submit_association_update.budget_2025; -- Variable ajoutée
  v_budget_2026 INTEGER := submit_association_update.budget_2026; -- Variable ajoutée
  v_nb_salaries SMALLINT := submit_association_update.nb_salaries;
  v_nb_benevoles SMALLINT := submit_association_update.nb_benevoles;
  v_nom_resp_edition TEXT := submit_association_update.nom_resp_edition;
  v_email_resp_edition TEXT := submit_association_update.email_resp_edition;
  v_email_org TEXT := submit_association_update.email_org;
  v_nom_contact TEXT := submit_association_update.nom_contact;
  v_tel_contact TEXT := submit_association_update.tel_contact;
  v_email_contact TEXT := submit_association_update.email_contact;
  v_website TEXT := submit_association_update.website;
  v_facebook TEXT := submit_association_update.facebook;
  v_twitter TEXT := submit_association_update.twitter;
  v_instagram TEXT := submit_association_update.instagram;
  v_linkedin TEXT := submit_association_update.linkedin;
  v_tiktok TEXT := submit_association_update.tiktok;
  v_autre_social_media TEXT := submit_association_update.autre_social_media;
  v_logo_url TEXT := submit_association_update.logo_url;
BEGIN
  -- Check user rights
  SELECT * INTO v_user_profile
  FROM public.user_profiles up
  WHERE up.id = auth.uid() AND up.edit_association_id = v_association_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION '403: Forbidden';
  END IF;

  -- Delete previous registered modifications
  DELETE FROM public.associations_maj am
  WHERE am.association_id = v_association_id 
    AND am.user_id = auth.uid();

  -- Insert new modification
  INSERT INTO public.associations_maj (
    association_id, 
    user_id, 
    nom,
    acronyme,
    "desc",
    type_org,
    type_org_autre,
    annee_creation,
    secteurs_interv,
    secteurs_interv_autre,
    province,
    territoire,
    zone_sante,
    aire_sante,
    localite,
    latitude,
    longitude,
    altitude,
    "precision",
    budget_2022,
    budget_2023,
    budget_2024,
    budget_2025,  -- Champ ajouté
    budget_2026,  -- Champ ajouté
    nb_salaries,
    nb_benevoles,
    nom_resp_edition,
    email_resp_edition,
    email_org,
    nom_contact,
    tel_contact,
    email_contact,
    website,
    facebook,
    twitter,
    instagram,
    linkedin,
    tiktok,
    autre_social_media,
    logo_url
  ) VALUES (
    v_association_id,
    auth.uid(), 
    v_nom,
    v_acronyme,
    v_desc,
    v_type_org,
    v_type_org_autre,
    v_annee_creation,
    v_secteurs_interv,
    v_secteurs_interv_autre,
    v_province,
    v_territoire,
    v_zone_sante,
    v_aire_sante,
    v_localite,
    v_latitude,
    v_longitude,
    v_altitude,
    v_precision,
    v_budget_2022,
    v_budget_2023,
    v_budget_2024,
    v_budget_2025,  -- Valeur ajoutée
    v_budget_2026,  -- Valeur ajoutée
    v_nb_salaries,
    v_nb_benevoles,
    v_nom_resp_edition,
    v_email_resp_edition,
    v_email_org,
    v_nom_contact,
    v_tel_contact,
    v_email_contact,
    v_website,
    v_facebook,
    v_twitter,
    v_instagram,
    v_linkedin,
    v_tiktok,
    v_autre_social_media,
    v_logo_url
  ) RETURNING id INTO v_modification_id;

  RETURN v_modification_id;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.submit_projet_update(association_id uuid, projet_id uuid, intitule_projet text, partenaire_financier_technique text, noms_bailleurs_fonds text[], autre_bailleur_fonds text, secteurs_intervention text[], autre_secteur_intervention text, date_debut_projet date, date_fin_projet date, statut_projet text, province text[], territoire text[], aire_sante text, zone_sante text[], localite_village_quartier text, budget_projet numeric, consortium boolean, partenaires_consortium text, types_services_fournis text[], autre_type_services_fournis text, types_beneficiaires_populations_cibles text[], autre_types_beneficiaires_populations_cibles text, nombre_total_personnes_cibles integer, nombre_hommes integer, nombre_femmes integer, nombre_filles integer, nombre_garcons integer, nombre_personnes_atteintes integer, nombre_personnes_handicapees integer, nombre_hommes_agees integer, nombre_femmes_agees integer)
 RETURNS bigint
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  v_user_profile RECORD;
  v_modification_id BIGINT;
  -- Déclarer des variables locales pour éviter l'ambiguïté
  v_association_id UUID := submit_projet_update.association_id;
  v_projet_id UUID := submit_projet_update.projet_id;
  v_intitule_projet TEXT := submit_projet_update.intitule_projet;
  v_partenaire_financier_technique TEXT := submit_projet_update.partenaire_financier_technique;
  v_noms_bailleurs_fonds TEXT[] := submit_projet_update.noms_bailleurs_fonds;
  v_autre_bailleur_fonds TEXT := submit_projet_update.autre_bailleur_fonds;
  v_secteurs_intervention TEXT[] := submit_projet_update.secteurs_intervention;
  v_autre_secteur_intervention TEXT := submit_projet_update.autre_secteur_intervention;
  v_date_debut_projet DATE := submit_projet_update.date_debut_projet;
  v_date_fin_projet DATE := submit_projet_update.date_fin_projet;
  v_statut_projet TEXT := submit_projet_update.statut_projet;
  v_province TEXT[] := submit_projet_update.province;
  v_territoire TEXT[] := submit_projet_update.territoire;
  v_aire_sante TEXT := submit_projet_update.aire_sante;
  v_zone_sante TEXT[] := submit_projet_update.zone_sante;
  v_localite_village_quartier TEXT := submit_projet_update.localite_village_quartier;
  v_budget_projet NUMERIC(15, 2) := submit_projet_update.budget_projet;
  v_consortium BOOLEAN := submit_projet_update.consortium;
  v_partenaires_consortium TEXT := submit_projet_update.partenaires_consortium;
  v_types_services_fournis TEXT[] := submit_projet_update.types_services_fournis;
  v_autre_type_services_fournis TEXT := submit_projet_update.autre_type_services_fournis;
  v_types_beneficiaires_populations_cibles TEXT[] := submit_projet_update.types_beneficiaires_populations_cibles;
  v_autre_types_beneficiaires_populations_cibles TEXT := submit_projet_update.autre_types_beneficiaires_populations_cibles;
  v_nombre_total_personnes_cibles INTEGER := submit_projet_update.nombre_total_personnes_cibles;
  v_nombre_hommes INTEGER := submit_projet_update.nombre_hommes;
  v_nombre_femmes INTEGER := submit_projet_update.nombre_femmes;
  v_nombre_filles INTEGER := submit_projet_update.nombre_filles;
  v_nombre_garcons INTEGER := submit_projet_update.nombre_garcons;
  v_nombre_personnes_atteintes INTEGER := submit_projet_update.nombre_personnes_atteintes;
  v_nombre_personnes_handicapees INTEGER := submit_projet_update.nombre_personnes_handicapees;
  v_nombre_hommes_agees INTEGER := submit_projet_update.nombre_hommes_agees;
  v_nombre_femmes_agees INTEGER := submit_projet_update.nombre_femmes_agees;
BEGIN
  -- Check user rights
  SELECT * INTO v_user_profile
  FROM public.user_profiles up
  WHERE up.id = auth.uid() AND up.edit_association_id = v_association_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION '403: Forbidden';
  END IF;

  -- Delete previous registered modifications
  DELETE FROM public.projets_maj pm
  WHERE pm.projet_id = v_projet_id;

  -- Insert new modification
  INSERT INTO public.projets_maj (
    association_id,
    projet_id,
    intitule_projet,
    partenaire_financier_technique,
    noms_bailleurs_fonds,
    autre_bailleur_fonds,
    secteurs_intervention,
    autre_secteur_intervention,
    date_debut_projet,
    date_fin_projet,
    statut_projet,
    province,
    territoire,
    aire_sante,
    zone_sante,
    localite_village_quartier,
    budget_projet,
    consortium,
    partenaires_consortium,
    types_services_fournis,
    autre_type_services_fournis,
    types_beneficiaires_populations_cibles,
    autre_types_beneficiaires_populations_cibles,
    nombre_total_personnes_cibles,
    nombre_hommes,
    nombre_femmes,
    nombre_filles,
    nombre_garcons,
    nombre_personnes_atteintes,
    nombre_personnes_handicapees,
    nombre_hommes_agees,
    nombre_femmes_agees
  ) VALUES (
    v_association_id,
    v_projet_id,
    v_intitule_projet,
    v_partenaire_financier_technique,
    v_noms_bailleurs_fonds,
    v_autre_bailleur_fonds,
    v_secteurs_intervention,
    v_autre_secteur_intervention,
    v_date_debut_projet,
    v_date_fin_projet,
    v_statut_projet,
    v_province,
    v_territoire,
    v_aire_sante,
    v_zone_sante,
    v_localite_village_quartier,
    v_budget_projet,
    v_consortium,
    v_partenaires_consortium,
    v_types_services_fournis,
    v_autre_type_services_fournis,
    v_types_beneficiaires_populations_cibles,
    v_autre_types_beneficiaires_populations_cibles,
    v_nombre_total_personnes_cibles,
    v_nombre_hommes,
    v_nombre_femmes,
    v_nombre_filles,
    v_nombre_garcons,
    v_nombre_personnes_atteintes,
    v_nombre_personnes_handicapees,
    v_nombre_hommes_agees,
    v_nombre_femmes_agees
  ) RETURNING id INTO v_modification_id;

  RETURN v_modification_id;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.submit_projet_update(association_id uuid, projet_id uuid, intitule_projet text, partenaire_financier_technique text, noms_bailleurs_fonds text[], autre_bailleur_fonds text, secteurs_intervention text[], autre_secteur_intervention text, date_debut_projet date, date_fin_projet date, statut_projet text, province text[], territoire text[], aire_sante text, zone_sante text[], localite_village_quartier text, budget_projet numeric, consortium boolean, partenaires_consortium text, types_services_fournis text[], autre_type_services_fournis text, types_beneficiaires_populations_cibles text[], autre_types_beneficiaires_populations_cibles text, nombre_total_personnes_cibles integer, nombre_hommes integer, nombre_femmes integer, nombre_filles integer, nombre_garcons integer, nombre_personnes_atteintes integer, nombre_personnes_handicapees integer, nombre_personnes_agees integer)
 RETURNS bigint
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  v_user_profile RECORD;
  v_modification_id BIGINT;
  -- Déclarer des variables locales pour éviter l'ambiguïté
  v_association_id UUID := submit_projet_update.association_id;
  v_projet_id UUID := submit_projet_update.projet_id;
  v_intitule_projet TEXT := submit_projet_update.intitule_projet;
  v_partenaire_financier_technique TEXT := submit_projet_update.partenaire_financier_technique;
  v_noms_bailleurs_fonds TEXT[] := submit_projet_update.noms_bailleurs_fonds;
  v_autre_bailleur_fonds TEXT := submit_projet_update.autre_bailleur_fonds;
  v_secteurs_intervention TEXT[] := submit_projet_update.secteurs_intervention;
  v_autre_secteur_intervention TEXT := submit_projet_update.autre_secteur_intervention;
  v_date_debut_projet DATE := submit_projet_update.date_debut_projet;
  v_date_fin_projet DATE := submit_projet_update.date_fin_projet;
  v_statut_projet TEXT := submit_projet_update.statut_projet;
  v_province TEXT[] := submit_projet_update.province;
  v_territoire TEXT[] := submit_projet_update.territoire;
  v_aire_sante TEXT := submit_projet_update.aire_sante;
  v_zone_sante TEXT[] := submit_projet_update.zone_sante;
  v_localite_village_quartier TEXT := submit_projet_update.localite_village_quartier;
  v_budget_projet NUMERIC(15, 2) := submit_projet_update.budget_projet;
  v_consortium BOOLEAN := submit_projet_update.consortium;
  v_partenaires_consortium TEXT := submit_projet_update.partenaires_consortium;
  v_types_services_fournis TEXT[] := submit_projet_update.types_services_fournis;
  v_autre_type_services_fournis TEXT := submit_projet_update.autre_type_services_fournis;
  v_types_beneficiaires_populations_cibles TEXT[] := submit_projet_update.types_beneficiaires_populations_cibles;
  v_autre_types_beneficiaires_populations_cibles TEXT := submit_projet_update.autre_types_beneficiaires_populations_cibles;
  v_nombre_total_personnes_cibles INTEGER := submit_projet_update.nombre_total_personnes_cibles;
  v_nombre_hommes INTEGER := submit_projet_update.nombre_hommes;
  v_nombre_femmes INTEGER := submit_projet_update.nombre_femmes;
  v_nombre_filles INTEGER := submit_projet_update.nombre_filles;
  v_nombre_garcons INTEGER := submit_projet_update.nombre_garcons;
  v_nombre_personnes_atteintes INTEGER := submit_projet_update.nombre_personnes_atteintes;
  v_nombre_personnes_handicapees INTEGER := submit_projet_update.nombre_personnes_handicapees;
  v_nombre_personnes_agees INTEGER := submit_projet_update.nombre_personnes_agees;
BEGIN
  -- Check user rights
  SELECT * INTO v_user_profile
  FROM public.user_profiles up
  WHERE up.id = auth.uid() AND up.edit_association_id = v_association_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION '403: Forbidden';
  END IF;

  -- Delete previous registered modifications
  DELETE FROM public.projets_maj pm
  WHERE pm.projet_id = v_projet_id;

  -- Insert new modification
  INSERT INTO public.projets_maj (
    association_id,
    projet_id,
    intitule_projet,
    partenaire_financier_technique,
    noms_bailleurs_fonds,
    autre_bailleur_fonds,
    secteurs_intervention,
    autre_secteur_intervention,
    date_debut_projet,
    date_fin_projet,
    statut_projet,
    province,
    territoire,
    aire_sante,
    zone_sante,
    localite_village_quartier,
    budget_projet,
    consortium,
    partenaires_consortium,
    types_services_fournis,
    autre_type_services_fournis,
    types_beneficiaires_populations_cibles,
    autre_types_beneficiaires_populations_cibles,
    nombre_total_personnes_cibles,
    nombre_hommes,
    nombre_femmes,
    nombre_filles,
    nombre_garcons,
    nombre_personnes_atteintes,
    nombre_personnes_handicapees,
    nombre_personnes_agees
  ) VALUES (
    v_association_id,
    v_projet_id,
    v_intitule_projet,
    v_partenaire_financier_technique,
    v_noms_bailleurs_fonds,
    v_autre_bailleur_fonds,
    v_secteurs_intervention,
    v_autre_secteur_intervention,
    v_date_debut_projet,
    v_date_fin_projet,
    v_statut_projet,
    v_province,
    v_territoire,
    v_aire_sante,
    v_zone_sante,
    v_localite_village_quartier,
    v_budget_projet,
    v_consortium,
    v_partenaires_consortium,
    v_types_services_fournis,
    v_autre_type_services_fournis,
    v_types_beneficiaires_populations_cibles,
    v_autre_types_beneficiaires_populations_cibles,
    v_nombre_total_personnes_cibles,
    v_nombre_hommes,
    v_nombre_femmes,
    v_nombre_filles,
    v_nombre_garcons,
    v_nombre_personnes_atteintes,
    v_nombre_personnes_handicapees,
    v_nombre_personnes_agees
  ) RETURNING id INTO v_modification_id;

  RETURN v_modification_id;
END;
$function$
;

  create policy "Admins control associations"
  on "public"."associations"
  as permissive
  for all
  to public
using (public.is_admin());



  create policy "Allow public read access"
  on "public"."associations"
  as permissive
  for select
  to public
using (true);



  create policy "Admins controls associations edition"
  on "public"."associations_maj"
  as permissive
  for all
  to public
using (public.is_admin());



  create policy "Users can see their modifications on associations"
  on "public"."associations_maj"
  as permissive
  for select
  to public
using ((user_id = auth.uid()));



  create policy "Users can update their changes on association"
  on "public"."associations_maj"
  as permissive
  for update
  to public
using ((user_id = auth.uid()))
with check ((user_id = auth.uid()));



  create policy "Admin controls new association"
  on "public"."associations_new"
  as permissive
  for all
  to public
using (public.is_admin())
with check (public.is_admin());



  create policy "Creator user can create a new asso"
  on "public"."associations_new"
  as permissive
  for insert
  to public
with check (public.check_user_is_creator());



  create policy "User can read his submission"
  on "public"."associations_new"
  as permissive
  for select
  to public
using ((created_by = auth.uid()));



  create policy "User can update his submission"
  on "public"."associations_new"
  as permissive
  for update
  to public
using ((created_by = auth.uid()))
with check ((created_by = auth.uid()));



  create policy "Admins control projects"
  on "public"."projets"
  as permissive
  for all
  to public
using (public.is_admin());



  create policy "Allow public read access"
  on "public"."projets"
  as permissive
  for all
  to public
using (true);



  create policy "Admin controls table"
  on "public"."projets_maj"
  as permissive
  for all
  to public
using (public.is_admin());



  create policy "Authenticated user can insert project"
  on "public"."projets_maj"
  as permissive
  for insert
  to public
with check (public.check_user_has_edit_association());



  create policy "User can read his submission"
  on "public"."projets_maj"
  as permissive
  for select
  to public
using ((created_by = auth.uid()));



  create policy "Users can update their changes on project"
  on "public"."projets_maj"
  as permissive
  for update
  to public
using ((created_by = auth.uid()))
with check ((created_by = auth.uid()));



  create policy "Admin controls new project"
  on "public"."projets_new"
  as permissive
  for all
  to public
using (public.is_admin())
with check (public.is_admin());



  create policy "Auth user can create new project"
  on "public"."projets_new"
  as permissive
  for insert
  to public
with check (public.check_user_has_edit_association());



  create policy "User can read his submission"
  on "public"."projets_new"
  as permissive
  for select
  to public
using ((created_by = auth.uid()));



  create policy "User can update their new project submission"
  on "public"."projets_new"
  as permissive
  for update
  to public
using ((created_by = auth.uid()))
with check ((created_by = auth.uid()));



  create policy "Enable read access for all users"
  on "public"."provinces"
  as permissive
  for select
  to public
using (true);



  create policy "Enable read access for all users"
  on "public"."territoires"
  as permissive
  for select
  to public
using (true);



  create policy "Admin can read users table"
  on "public"."user_profiles"
  as permissive
  for select
  to public
using (public.is_admin());



  create policy "Update profiles policy"
  on "public"."user_profiles"
  as permissive
  for update
  to public
using (((auth.uid() = id) OR (EXISTS ( SELECT 1
   FROM public.user_profiles user_profiles_1
  WHERE ((user_profiles_1.id = auth.uid()) AND (user_profiles_1.role = 'admin'::public.user_roles))))))
with check (((EXISTS ( SELECT 1
   FROM public.user_profiles user_profiles_1
  WHERE ((user_profiles_1.id = auth.uid()) AND (user_profiles_1.role = 'admin'::public.user_roles)))) OR ((auth.uid() = id) AND (role = ( SELECT user_profiles_1.role
   FROM public.user_profiles user_profiles_1
  WHERE (user_profiles_1.id = auth.uid()))))));



  create policy "Users can see their profile"
  on "public"."user_profiles"
  as permissive
  for select
  to public
using ((auth.uid() = id));



  create policy "insert_own_profile"
  on "public"."user_profiles"
  as permissive
  for insert
  to public
with check ((auth.uid() = id));



  create policy "Enable read access for all users"
  on "public"."zones_sante"
  as permissive
  for select
  to public
using (true);


CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();